### ISSUE TITLE
Changing the not equal operator

### ISSUE THREAD

**Issue by vmx** [pipedown/noise#31]
I've had already two people telling me that that would prefer having not equal `!=` rather than the JavaScript like `!==`.

To explain where it comes from: equal is `==` and then you just put a `!` in front to have it negated. Hence `!==`. Though I agree that `!=` is way more common.

[One proposal](https://twitter.com/jnelas/status/864109179233075200) went even as far as proposing `=` for equal. I don't agree with that. I always found that confusing when I saw that in SQL.

Although I'm a huge fan of "there's only one way" I propose having `!=` *and* `!==` being the same. So you have the symmetry between `==` -> `!==` and `~-` -> `!~=` (do we support that already?), but also the more common `!=`.

What do others think?

**Comment by adagios** [comment]
Just to clarify my opinion: It it's a query language, and there's no need for an assignment operator, equal (`=`) and not equal (`!=`) seem like the simplest choice. There's no ambiguity because there's never an assignment.

But, I never really had a problem with SQL :) so, that's my bias.

Having `!=` and `!==` only makes sense to me to seem more approachable to people coming from js.

Having said this, it's a little bit of bike-shedding and neither of the options with really bug me.

**Comment by Damienkatz** [comment]
fixed in a30dbe48345a595db2d88b770480454ac4782c99
